/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * Appcelerator Titanium Mobile
 * Copyright (c) 2009-2013 by Appcelerator, Inc. All Rights Reserved.
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 *
 */
package com.exygy.androidzerotableviewseparator;
import org.appcelerator.kroll.KrollModule;
import org.appcelerator.kroll.annotations.Kroll;
import org.appcelerator.titanium.TiApplication;
import org.appcelerator.kroll.common.Log;
import ti.modules.titanium.ui.TableViewProxy;
import ti.modules.titanium.ui.widget.TiUITableView;
import ti.modules.titanium.ui.widget.tableview.TiTableView;
import android.widget.ListView;


// SEE THE FOLLOWING URL FOR MORE EXPLANATION
//http://developer.appcelerator.com/question/137789/set-android-tableview--listview-divider-height-to-0


@Kroll.module(name="AndroidZeroTableViewSeparator", id="com.exygy.androidzerotableviewseparator")
public class AndroidZeroTableViewSeparatorModule extends KrollModule
{

	// Standard Debugging variables
	private static final String TAG = "AndroidZeroTableViewSeparatorModule";

	// You can define constants with @Kroll.constant, for example:
	// @Kroll.constant public static final String EXTERNAL_NAME = value;
	
	public AndroidZeroTableViewSeparatorModule()
	{
		super();
	}

	@Kroll.onAppCreate
	public static void onAppCreate(TiApplication app)
	{
		Log.d(TAG, "AndroidZeroTableViewSeparatorModule created");
	}

	// Methods
	@Kroll.method
	public void hideTableRowSepartor(TableViewProxy tableViewProxy)
	{
	    ListView tableListView = tableViewProxy.getTableView().getListView();
	    tableListView.setDividerHeight(0);
	}
}

